stages:
  - quality
  - build-services
  - build-stack
  - upload-stack
  - deploy
  - approval
  - deploy-preprod
  - approval-to-prod
  - approval-ops
  - deploy-prod
.job_build_template:
  image: '${CI_STACK_BUILDER_STABLE_IMAGE}'
.job_upload_template:
  image: '${CI_STACK_UPLOADER_STABLE_IMAGE}'
  dependencies: &ref_0
    - 'build:stack'
  script: &ref_1
    - uploader
  allow_failure: false
.job_deploy_template:
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: &ref_2
    - 'build:stack'
  script: &ref_3
    - deployer
  when: manual
.job_only_tags:
  only: &ref_4
    - tags
.job_approval_template:
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: &ref_5
    - tags
  variables: &ref_6
    APPROVAL_TYPE: approve
  script: &ref_7
    - auth-checker
  when: manual
.job_rejected_template:
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: &ref_8
    - tags
  variables: &ref_9
    APPROVAL_TYPE: reject
  script: &ref_10
    - auth-checker
  when: manual
'build:offboarding':
  image: '${CI_STACK_BUILDER_STABLE_IMAGE}'
  stage: build-services
  script:
    - build-services offboarding
'test:jest':
  image: 'node:16-alpine'
  stage: quality
  cache:
    paths:
      - offboarding/node_modules/
  script:
    - cd offboarding
    - 'npm config set @geopagos:registry http://npm.geopagoslan.net'
    - yarn
    - yarn test
'build:stack':
  image: '${CI_STACK_BUILDER_STABLE_IMAGE}'
  stage: build-stack
  artifacts:
    paths:
      - dist
  script:
    - build-stack
'upload:stack':
  image: '${CI_STACK_UPLOADER_STABLE_IMAGE}'
  dependencies: *ref_0
  script: *ref_1
  allow_failure: false
  stage: upload-stack
'deploy:dev':
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: *ref_2
  script: *ref_3
  when: manual
  stage: deploy
  environment: dev
'deploy:sandbox':
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: *ref_2
  script: *ref_3
  when: manual
  only: *ref_4
  stage: deploy
  environment: sandbox
'deploy:test':
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: *ref_2
  script: *ref_3
  when: manual
  only: *ref_4
  stage: deploy
  environment: test
'deploy:testvolatil':
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: *ref_2
  script: *ref_3
  when: manual
  only: *ref_4
  stage: deploy
  environment: testvolatil
'approval:QA':
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: *ref_5
  variables: *ref_6
  script: *ref_7
  when: manual
  stage: approval
'approval:RQA':
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: *ref_5
  variables: *ref_6
  script: *ref_7
  when: manual
  stage: approval
'rejected:QA':
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: *ref_8
  variables: *ref_9
  script: *ref_10
  when: manual
  stage: approval
'deploy:preprod':
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: *ref_2
  script: *ref_3
  when: manual
  only: *ref_4
  stage: deploy-preprod
  environment: preprod
'deploy:demo':
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: *ref_2
  script: *ref_3
  when: manual
  only: *ref_4
  stage: deploy-preprod
  environment: demo
'approval:TL':
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: *ref_5
  variables: *ref_6
  script: *ref_7
  when: manual
  stage: approval-to-prod
'approval:PM':
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: *ref_5
  variables: *ref_6
  script: *ref_7
  when: manual
  stage: approval-to-prod
'approval:OP':
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: *ref_5
  variables: *ref_6
  script: *ref_7
  when: manual
  stage: approval-ops
  allow_failure: false
'rejected:OP':
  image: '${CI_APPROVAL_STABLE_IMAGE}'
  only: *ref_8
  variables: *ref_9
  script: *ref_10
  when: manual
  stage: approval-ops
'deploy:prod':
  image: '${CI_FULL_DEPLOYER_STABLE_IMAGE}'
  dependencies: *ref_2
  script: *ref_3
  when: manual
  only: *ref_4
  stage: deploy-prod
  environment: prod
