version: "3.4"

services:
  "offboarding":
    "dns": "8.8.8.8"
    "image": "${IMAGE:offboarding}"
    "environment":
      # COMMON
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}

      # VIUMI
      - TENANT-VIUMI_ENABLED=${TENANT-VIUMI_ENABLED}
      - VIUMI_DASHBOARD_DOMAIN=${VIUMI_DASHBOARD_DOMAIN}
      - VIUMI_BACKEND_DOMAIN=${VIUMI_BACKEND_DOMAIN}
      - VIUMI_API_DOMAIN=${VIUMI_API_DOMAIN}
      - VIUMI_DOMAIN=${VIUMI_DOMAIN}
      - VIUMI_TENANT_NAME=${VIUMI_TENANT_NAME}
    "deploy":
      "mode": "replicated"
      "replicas": 2
      "restart_policy":
        "condition": "any"
      "labels":
        "traefik.protocol": "http"
        "traefik.port": "3000"
        "traefik.enable": "true"
        "traefik.backend.loadbalancer.swarm": "true"
        "traefik.docker.lbswarm": "true"
        "traefik.http.services.${ENVIRONMENT}_offboarding-${VIUMI_TENANT_NAME}.loadbalancer.server.port": "3000"
        # VIUMI
        "traefik.http.routers.${ENVIRONMENT}_${VIUMI_TENANT_NAME}.rule": "Host(`${VIUMI_DOMAIN}`) && Path(`/`)"
        "traefik.http.routers.${ENVIRONMENT}_${VIUMI_TENANT_NAME}.entrypoints": "web,websecure"
        "traefik.http.routers.${ENVIRONMENT}_${VIUMI_TENANT_NAME}.middlewares": "security@file"
        "traefik.http.middlewares.${ENVIRONMENT}_${VIUMI_TENANT_NAME}.replacepath.path": "/${VIUMI_TENANT_NAME}"

        # VIUMI - COMMON
        "traefik.http.routers.${ENVIRONMENT}_${VIUMI_TENANT_NAME}-common.rule": 'Host(`${VIUMI_DOMAIN}`) && PathPrefix(`/assets`,`/_app`,`/viumi`,`/api`)'
        "traefik.http.routers.${ENVIRONMENT}_${VIUMI_TENANT_NAME}-common.middlewares": '${ENVIRONMENT}-viumi@docker'

      "placement":
        "constraints":
          - "node.labels.type == ${WORKER_COMPUTE_TYPE}"
    "logging":
      "driver": "gelf"
      "options":
        "gelf-address": "udp://localhost:12204"
        "tag": "${ENVIRONMENT}-offboarding"
    "networks":
      - "${NETWORK}"

networks:
  ${NETWORK}:
    external: true
